# Generated by Django 5.2.7 on 2025-11-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_officer', '0002_electionposition'),
        ('nacos_app', '0002_alter_customuser_email_alter_customuser_matric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election Position',
                'verbose_name_plural': 'Election Positions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='electiontimeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_timelines', to='election_officer.electionofficer'),
        ),
    ]
