# Generated by Django 5.2.7 on 2025-11-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0003_electionposition_alter_electiontimeline_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electiontimeline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='electiontimeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
