# Generated by Django 5.2.7 on 2025-11-03 09:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0004_alter_electiontimeline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 9, 29, 56, 924962, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='account_statement',
            field=models.FileField(default='', upload_to='contest/accounts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='manifesto',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nacos_app.electionposition'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='statement_of_result',
            field=models.FileField(default='', upload_to='contest/results/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
