# Generated by Django 5.2.7 on 2025-11-04 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0005_remove_contestapplication_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nacos_app.contestapplication')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nacos_app.electiontimeline')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nacos_app.electionposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-voted_at'],
                'indexes': [models.Index(fields=['user', 'election'], name='nacos_app_v_user_id_c2bb9d_idx'), models.Index(fields=['candidate'], name='nacos_app_v_candida_250d34_idx'), models.Index(fields=['election', 'position'], name='nacos_app_v_electio_816a2d_idx')],
                'unique_together': {('user', 'election', 'position')},
            },
        ),
    ]
