# Generated by Django 5.2.7 on 2025-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.TextField(blank=True, default='Mathematics and Computer Science'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.TextField(blank=True, default='Science'),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='allow_all_candidates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='allow_all_voters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='candidate_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='candidate_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='show_live_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='voter_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='electiontimeline',
            name='voter_levels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
