# Generated by Django 5.2.7 on 2025-11-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0007_customuser_department_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiontimeline',
            name='allow_all_candidates',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='allow_all_voters',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='candidate_departments',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='candidate_levels',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='show_live_results',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='voter_departments',
        ),
        migrations.RemoveField(
            model_name='electiontimeline',
            name='voter_levels',
        ),
    ]
