# Generated by Django 5.2.7 on 2025-11-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nacos_app', '0008_remove_electiontimeline_allow_all_candidates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='faculty',
        ),
    ]
