# Generated by Django 5.2.7 on 2025-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election Position',
                'verbose_name_plural': 'Election Positions',
                'ordering': ['name'],
            },
        ),
    ]
